---
apiVersion: v1
kind: Pod
metadata:
  name: nameofbot
  namespace: default
  labels:
    app: nameofbot
spec:
  containers:
    - name: nameofbot
      image: devopsbasservice/ubuntu4bot:v2
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "sleep infinity" ]
      ports:
        - containerPort: 8787
      env:
        - name: MY_POD_NAME
          valueFrom:
           fieldRef:
            fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
           fieldRef:
            fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
  restartPolicy: Never 
